version: "3"

services:
    postgres:
        image: postgres:alpine
        ports:
        - "5433:5433"
        volumes:
        - ./dbdata:/var/lib/postgresql/data
        environment:
        - POSTGRES_PASSWORD=docker

    covid:
        build:
            context: ../
            dockerfile: ./docker/dockerfile
        ports:
            - "8181:5433"
version: "3"

services:
    app:
        container_name: full_app
        build: .
        ports: 
          - 8080:8080 
        restart: on-failure
        volumes:
          - api:/usr/src/app/
        depends_on:
          - fullstack-postgres
        networks:
          - fullstack

    fullstack-postgres:
        image: postgres:latest
        container_name: full_db_postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=covidprovinsi
            - DATABASE_HOST=127.0.0.1
        ports:
            - '5432:5432'
        volumes:
            - database_postgres:/var/lib/postgresql/data
        networks:
            - fullstack

volumes:
    api:
    database_postgres:  

networks:
    fullstack: 
        driver: bridge